#!/usr/bin/env python
from __future__ import division
import sys
import math
from gui import *
from geode.value import parser, PropManager
from geode import *
from geode.openmesh import *
from geode.random import *
from OpenGL import GL, GLUT
from numpy import *
from props import props
from follow import *

from kinematic_chain import *

angle_path = [];

'''Things to do: 
1. Pass in the origins and the goals correctly. 
2. Render the path correctly. 
'''

armset1 = System([Arm('a1',6,effector_functions)])

obstacle_arm_frame = Frames(array([1543,0,0]),Rotation.from_angle_axis(0,array([0,0,1])))
obstacle_arm = System([Arm('obstacle',6,effector_functions,bf=obstacle_arm_frame)])

armset_dummy = System([Arm('a2',6,effector_functions)])
dummy2 = Arm('obstacle2',6,effector_functions,bf=obstacle_arm_frame)

def update():
  frame = props.get("frame")()
  state = angle_path[int(frame)]
  for arm in armset1.arms:
    for i, node in enumerate(arm.nodes):
      node.rotation.set(float(state[i]) * 180/pi)
  for arm in obstacle_arm.arms:
    for j , node in enumerate(arm.nodes):
      node.rotation.set(float(state[j+6] * 180/pi))



def view():
  # Set up main window
  global angle_path
  app = QEApp(sys.argv,True)
  main = MainWindow(props)
  #We're going to add some windows
  ks = KukaScene(armset1)
  ks2 = KukaScene(obstacle_arm)
  main.view.add_scene("kuka",ks)
  main.view.add_scene("kuka",ks2)
  main.view.show_all(True)


  goal = armset_dummy.update_effector()
  goal2 = System([dummy2]).update_effector()
  both_goals = append(goal, goal2)
  print both_goals

  dimension = 12

  robot_origins = asarray(get_origins())
  robot_origins2 = asarray(get_origins()) + array([1543, 0, 0])
  both_origins = array([robot_origins, robot_origins2])

  print both_origins

  both_meshes = []
  for arm in armset1.arms:
    both_meshes.append(arm.submeshes())
  for arm in obstacle_arm.arms:
    both_meshes.append(arm.submeshes())
  print both_meshes



  if len(both_goals) == dimension:
    angle_path = plan(6,2, both_goals, both_origins, both_meshes)
    print angle_path
    props.get("last_frame").set(len(angle_path))
  
  main.resize_timeline(100);
  #kukaview = main.add_view("kuka")
 #Turn on the listener for props.get("frame"), then calls update (timeline updating)
  l = listen(props.get("frame"),update)

  # Launch
  main.init()
  app.run()

def main():
  #Pulls the properties for props
  parser.parse(props,'visualizer')
  view()
 
if __name__=='__main__':
  main()
