#!/usr/bin/env python
from __future__ import division
import sys
import math
from gui import *
from geode.value import parser, PropManager
from geode import *
from geode.openmesh import *
from geode.random import *
from OpenGL import GL, GLUT
from numpy import *
from props import props
from follow import *
from math import *
from scatter3d_demo import *
from kinematic_chain import *

angle_path = [];

'''Things to do: 
1. Pass in the origins and the goals correctly. 
2. Render the path correctly. 
'''

def generate_targets(point, axis):
  axis = normalized(asarray(axis))
  axis2 = unit_orthogonal_vector(axis);
  axis3 = normalized(cross(axis2, axis))
  p1 = [];
  p1.append(point + axis3 * sqrt(25**2 + 25**2))
  p1.append(point + axis2 * 25+ axis3 * -25)
  p1.append(point + axis2 * -25 + axis3 * -25)
  return asarray(p1);


target_point = [1000, 0, 1000];
target_axis = [0, 0, 1]
location = array([1800, 0,0])



armset1 = System([Arm('a1',6, effector_functions)], generate_targets(target_point, target_axis))
armset_dummy = System([Arm('a2',6,effector_functions)], generate_targets(target_point, target_axis))
   
obstacle_arm_frame = Frames(location,Rotation.from_angle_axis(pi/2,array([0,0,1])))
obstacle_arm = System([Arm('obstacle',6,effector_functions2,bf=obstacle_arm_frame)], generate_targets(target_point, target_axis))
armset_dummy2 = System([Arm('obstacle2',6,effector_functions2,bf=obstacle_arm_frame)], generate_targets(target_point, target_axis))


def update():
  frame = props.get("frame")()
  state = angle_path[int(frame)]
  for arm in armset1.arms:
    for i, node in enumerate(arm.nodes):
      node.rotation.set(float(state[i]) * 180/pi)
  for arm in obstacle_arm.arms:
    for j , node in enumerate(arm.nodes):
      node.rotation.set(float(state[j+6] * 180/pi))



def view():
  # Set up main window
  global angle_path
  global location

  app = QEApp(sys.argv,True)
  main = MainWindow(props)
  #We're going to add some windows
  ks = KukaScene(armset1)
  ks2 = KukaScene(obstacle_arm)
  main.view.add_scene("kuka",ks)
  main.view.add_scene("kuka",ks2)
  main.view.show_all(True)

  
  phi = (1 + sqrt(5))/2
  goal_list = [];
  angle_goals = [];
  for t in range(1, 2):
    #p1 = [1250, 0, 1000];
    p1 = array([1250, 0, 1000 + 400 * (-2*t +1)]) #500 + 400*cos(pi/10 * t), 1425 + 300*sin(pi/10 *t)])
    goal_list.append(p1)
    coarse_samples = []
    target_list = []
    for sign1 in [-1, 1]:
      for sign2 in [-1, 1]:
        for i in range(0, 3):
          target_axis = [0, 0, 0]
          target_axis[i] = phi* sign1
          target_axis[i-1] = sign2
        #  print target_axis
         #  target_list.append(target_axis)
          armset_dummy.set_target(generate_targets(p1, target_axis))
          armset_dummy2.set_target(generate_targets(p1, target_axis))
          goal = armset_dummy.solve_ik()
          goal2 = armset_dummy2.solve_ik()
          final_configuration = append(goal, goal2)
          coarse_samples.append(final_configuration)
    angle_goals.append(coarse_samples)

  print goal_list
  print angle_goals
  robot_origins = asarray(get_origins())
  robot_origins2 = asarray(get_origins());
  both_origins = array([robot_origins, robot_origins2])

  both_meshes = []
  for arm in armset1.arms:
    both_meshes.append(arm.submeshes())
  for arm in obstacle_arm.arms:
    both_meshes.append(arm.submeshes())
 

#static Nested<real> plan(unsigned int links, double robot_number, vector<Array<real>> goalState, 
#Array<Vector<real,3>,2> parsed_offsets, vector<vector<Ref<TriMesh>>> robotMeshes, vector<Ref<TriMesh>> obstacleMeshes, 
#double resolution, double range, double solve_time, double initial_angle, initial locations, tolerance) 

  angle_path = plan_goals(6,2, goal_list, both_origins, both_meshes, [bunny()], .1, 10 , 30., pi/2, [array([0, 0, 0]), location], 1, angle_goals)
 # print angle_path

  props.get("last_frame").set(len(angle_path))
  
  main.resize_timeline(100);
 # plot_points(angle_path)
#  kukaview = main.add_view("kuka")
 #Turn on the listener for props.get("frame"), then calls update (timeline updating)
  l = listen(props.get("frame"),update)

  # Launch
  main.init()
  app.run()

def main():
  #Pulls the properties for props
  parser.parse(props,'visualizer')
  view()
 
if __name__=='__main__':
  main()
